[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
chrono = "0.4.33"
reqwest = "0.11.23"
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
tokio = { version = "1.35.1", features = ["full"] }
